name: "master"

on:
  push:
    branches:
      - master
      - feature/*
  pull_request:
    branches:
      - master
      - feature/*

jobs:
  job_windows:
    name: "Build for Windows"
    runs-on: 'windows-latest'
    steps:
      - name: "Git Clone"
        uses: "actions/checkout@v2"
      - name: "Setup JDK"
        uses: "actions/setup-java@v1"
        with:
          java-version: "11"
          architecture: "x64"
      - name: "Gradle Windows"
        shell: cmd
        run: |
          gradlew.bat buildWindows
      - name: "Upload Windows build"
        uses: "actions/upload-artifact@v1"
        with:
          name: "windows"
          path: "build/distributions/TOTPClient.zip"


  job_mac:
    name: "Build for Mac"
    runs-on: 'macos-latest'
    steps:
      - name: "Git Clone"
        uses: "actions/checkout@v2"
      - name: "Setup JDK"
        uses: "actions/setup-java@v1"
        with:
          java-version: "11"
          architecture: "x64"
      - name: "Gradle Mac"
        run: |
          chmod +x ./gradlew
          ./gradlew buildMac
      - name: "Upload Mac build"
        uses: "actions/upload-artifact@v1"
        with:
          name: "mac"
          path: "build/distributions/TOTPClient.tar.gz"

  job_linux:
    name: "Build for Linux"
    runs-on: 'ubuntu-latest'
    steps:
      - name: "Git Clone"
        uses: "actions/checkout@v2"
      - name: "Setup JDK"
        uses: "actions/setup-java@v1"
        with:
          java-version: "11"
          architecture: "x64"
      - name: "Gradle Linux"
        run: |
          chmod +x ./gradlew
          ./gradlew buildLinux
      - name: "Upload Linux build"
        uses: "actions/upload-artifact@v1"
        with:
          name: "linux"
          path: "build/distributions/TOTPClient.tar.gz"
