name: "master"

on:
  push:
    branches:
      - master
      - feature/*
  pull_request:
    branches:
      - master
      - feature/*

jobs:
  job_windows:
    name: "Build for Windows"
    runs-on: 'windows-latest'
    steps:
      - name: "Git Clone"
        uses: "actions/checkout@v2"
      - name: "Setup Visual Studio env"
        uses: "ilammy/msvc-dev-cmd@v1"
      - name: "Setup GraalVM"
        uses: "DeLaGuardo/setup-graalvm@3"
        with:
          graalvm-version: "20.1.0.java11"
      - name: "Setup Native Image"
        shell: cmd
        run: |
          gu install native-image
      - name: "Gradle build"
        shell: cmd
        run: |
          gradlew.bat build
      - name: "Expand-Archive"
        shell: pwsh
        run: |
          Expand-Archive -Path build\distributions\totp-1.0-SNAPSHOT.zip
      - name: "Native Image"
        shell: cmd
        run: |
          native-image --class-path "totp-1.0-SNAPSHOT\totp-1.0-SNAPSHOT\lib\*" "info.repy.totp.TOTPClient"
      - name: "Upload Windows build"
        uses: "actions/upload-artifact@v1"
        with:
          name: "windows"
          path: "TOTPClient.exe"

  job_mac:
    name: "Build for Mac"
    runs-on: 'macos-latest'
    steps:
      - name: "Git Clone"
        uses: "actions/checkout@v2"
      - name: "Setup JDK"
        uses: "actions/setup-java@v1"
        with:
          java-version: "11"
          architecture: "x64"
      - name: "Gradle Mac"
        run: |
          chmod +x ./gradlew
          ./gradlew buildMac
      - name: "Upload Mac build"
        uses: "actions/upload-artifact@v1"
        with:
          name: "mac"
          path: "build/distributions/TOTPClient.tar.gz"

  job_linux:
    name: "Build for Linux"
    runs-on: 'ubuntu-latest'
    steps:
      - name: "Git Clone"
        uses: "actions/checkout@v2"
      - name: "Setup JDK"
        uses: "actions/setup-java@v1"
        with:
          java-version: "11"
          architecture: "x64"
      - name: "Gradle Linux"
        run: |
          chmod +x ./gradlew
          ./gradlew buildLinux
      - name: "Upload Linux build"
        uses: "actions/upload-artifact@v1"
        with:
          name: "linux"
          path: "build/distributions/TOTPClient.tar.gz"
